name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - 
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL1: https://cloud189-shzh-person.oos-gdsz.ctyunapi.cn/e71f728c-ef1b-4380-b9a4-49daacdf2c5c?x-amz-CLIENTTYPEIN=UNKNOWN&AWSAccessKeyId=18bd696e8df5d7a48893&x-amz-UID=733920062&x-amz-APPID=828221&response-content-disposition=attachment%3Bfilename%3D%22WeebProjekt-2.1.0%2B-20201121-R-OFFICIAL.zip%22&x-amz-CLIENTNETWORK=UNKNOWN&x-amz-CLOUDTYPEIN=PERSON&x-amz-limit=rate%3D10240%2Cconcurrency%3D20&Signature=QPGcJMkNs3RhMaHMyYP5YVmSjTA%3D&x-amz-SHID=170500628&Expires=1606669496&x-amz-FSIZE=1113536554&x-amz-UFID=61325212182551428
  ROM_NAME: Generic
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Cleaning up
         run: |
           docker rmi `docker images -q`

       - name: Cloning ErfanGSIs tools
         run: |
            git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
            sudo chmod -R 777 ErfanGSIs
            curl -sL https://git.io/file-transfer | sh
             
       - name: Setting up Porting Environment
         run: |
           cd ErfanGSIs
           sudo apt update
           sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
           sudo ./ErfanGSIs/url2GSI.sh --ab $ROM_URL1 $ROM_NAME
           ls /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/
           7z a -r gsi.7z /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/*-AB-11-*-ErfanGSI.img
           sudo ./transfer wet gsi.7z
           sudo rm gsi.7z
           7z a -r gsi-aonly.7z /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/*-Aonly-*-ErfanGSI.img
           sudo ./transfer wet gsi-aonly.7z
