name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - 
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL1: https://cloud189-liaoning-person.oos-lnsy.ctyunapi.cn/PERSONCLOUD/b7311158-55db-4ba4-b6e1-0a78275860f7?x-amz-CLIENTTYPEIN=UNKNOWN&AWSAccessKeyId=532482dfdc85e5d60592&x-amz-UID=733920062&x-amz-APPID=828221&response-content-disposition=attachment%3Bfilename%3D%22miuipro_v10.0_ginkgo_20.11.5_patched_fix-en%2Cvi%2Cbr.zip%EF%BC%88%E5%89%AF%E6%9C%AC%EF%BC%89%22&x-amz-CLIENTNETWORK=UNKNOWN&x-amz-CLOUDTYPEIN=PERSON&x-amz-limit=rate%3D10240%2Cconcurrency%3D15&Signature=KZg/IiH0r4brGDRDQ%2Brow4MTEAo%3D&x-amz-SHID=170662734&Expires=1608109795&x-amz-FSIZE=2012263209&x-amz-UFID=71417112287906580
  ROM_NAME: MIUI
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Cleaning up
         run: |
           docker rmi `docker images -q`

       - name: Cloning ErfanGSIs tools
         run: |
            git clone --recurse-submodules https://github.com/tianwen22/ErfanGSIs.git
            sudo chmod -R 777 ErfanGSIs
            curl -sL https://git.io/file-transfer | sh
             
       - name: Setting up Porting Environment
         run: |
           cd ErfanGSIs
           sudo apt update
           sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
           sudo ./ErfanGSIs/url2GSI.sh --ab $ROM_URL1 $ROM_NAME
           ls /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/
           7z a -r gsi.7z /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/*-AB-*-ErfanGSI.img
           sudo ./transfer wet gsi.7z
           sudo rm gsi.7z
           7z a -r gsi-aonly.7z /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/*-Aonly-*-ErfanGSI.img
           sudo ./transfer wet gsi-aonly.7z
